.TH LUNAS "1" "Aug 2024"

.SH  NAME
.B lunas
-  A syncing cli tool that can handle more than two directories locally and remotely

.SH USAGE
.B NOT READY !

.SH OPTIONS
.TP
.B [-p, --path] <dir>

path of the directory to be synced. this option can be used many times to sync multiple directories

.TP
.B [-s, -src, --source] </path/to/dir>

path of the source local directory. this option can be used many times to sync multiple directories

.TP
.B [-d, -dest, --destination] </path/to/dir>

path of the destination local directory. this option can be used many times to sync multiple directories

.TP
.B [-r, --remote-path] <user@ip:/path/to/dir>

path of the remote sftp directory to be synced. this option can be used many times to sync multiple directories

.TP
.B [N=NUMBER, port=NUMBER]

the port number. this option, if used, must come after the relevant remote path. It defaults to 22, if the option is not used
        example: -rdest user@ip:/path/to/dir port=NUMBER

.TP
.B [pw=PASSWORD, password=PASSWORD]

password of the remote directory, this option, if used, must come after the relevant remote path.
otherwise, you should be prompted for the password if publickey authentication wasn't successful

        example:  -r user@ip:/path/to/dir port=NUMBER password=PASSWORD
        example:  -r user@ip:/path/to/dir pw=PASSWORD N=NUMBER

.TP
.B [-rs, -rsrc, --remote-source] <user@ip:/path/to/dir>

path of the remote source sftp directory. this option can be used many times to sync multiple directories

.TP
.B [-rd, -rdest, --remote-destination] <user@ip:/path/to/dir>

path of the remote destination sftp directory. this option can be used many times to sync multiple directories

.TP
.B [-C, --compression]

enable compression in remote transfer, zlib is used

.TP
.B [-CL, --compression-level]

chose the compression level, 1-9, 9 being the most efficient but slower

.TP
.B [-mkdir, --make-directory]

make any input directory if it doesn't exists, locally and remotely

.TP
.B [-x, --exclude] <relative/path/inside/input/dir>

exclude a path from getting synced. this option can be used many times to *exclude* multiple directories/files

	# only relative path starting from inside the input dir '/dir1/dir2/' like dir3/dir or dir3/file is allowed
.br

		example:  -r user@ip:/dir1/dir2/ -x dir3/dir -x dir3/file -x this_file_is_inside_dir2
.br
		example:  -p /dir1/dir2/ -x dir3/dir -x dir3/file -x dir3/dir4/dir5 -x this_dir_is_inside_dir2
.br

	# a /full/path or regular ./relative/paths aren't allowed, and would get ignored
.br

.TP
.B [-F, --fsync]

synchronize the copied file with the filesystem

.TP
.B [-L, --dereference]

follow symlinks. sync the target the symlink is pointing to instead of the symlink itself

.TP
.B [-R, --resume]

resume interrupted file transfer. enabled by default

files are copied to 'file.HASH.ls.part' before they are renamed to their original name 'file', HASH = hash(full_path_of_src + its_mtime) 

this is done to ensure if the src of an interrupted file was modified or --rollback was used instead of --update with multiple 
.br
input paths it doesn't resume with a wrong src

in case the srcs for 'file.HASH.ls.part' didn't produce the same HASH, it is considered orphaned and removed

if no src was found to check, then 'file.HASH.ls.part' is ignored

if 'file' and 'file.HASH.ls.part' both exists at destination and 'file' has the same mtime of its src, then the 'file.HASH.ls.part' is removed

.TP
.B [-u, --update]

check mtime of files and re-sync the file if mtime wasn't the same. this option enables -a mtime. the destination file, if exists, gets removed then re-synced again. it replaces old mtime files with newer mtime ones.

[-rb, --rollback] can be used to replace newer files with older ones

        example: -s /path/to/dir -rd user@ip:/path/to/dir port=NUMBER -u
        example:  -p /path/to/dir -p /path/to/dir2 -p /path/to/dir3 user@ip:/path/to/dir4 port=NUMBER pw=PASSWORD -u

.TP
.B [-P, --progress]

enable progress bar for copied files

.TP
.B [-v, --verbose]

print the source of which files/dirs were copied from not just the destination

.TP
.B [-q, --quiet]

disable print statements and only print errors

.TP
.B [-dr, --dry-run]

outputs what would be synced without actually syncing them

.TP
.B [--author]

print the program's author

.TP
.B [-h, --help]

print the help statement


.SH AUTHOR
.PP 

nodeluna - nodeluna@proton.me

https://github.com/nodeluna
